//! Module 7 — Combo preset CRUD + launch.
//!
//! Stored under `~/.agentdesk/presets/{id}.json`. Reads and writes
//! use the same atomic tmp-file-and-rename pattern as template and
//! workflow storage. Launching a preset walks its items in order and
//! calls `terminal_launcher::launch_agent_with_prompt` for each one —
//! failures on individual items are recorded but do not abort the
//! rest of the launch, because a half-launched combo is still useful
//! to the user (they see which terminals came up and which didn't).

use crate::models::{AgentTemplate, ComboPreset};
use crate::services::{template_manager, terminal_launcher};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

/// Directory where preset JSON files live: `~/.agentdesk/presets/`.
fn presets_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".agentdesk")
        .join("presets")
}

fn preset_path(id: &str) -> PathBuf {
    presets_dir().join(format!("{}.json", sanitize_id(id)))
}

/// Strip characters that would let a maliciously-edited id escape the
/// presets directory. Ids generated by `ComboPreset::new` are already
/// safe, but we never trust on-disk state.
fn sanitize_id(id: &str) -> String {
    id.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-')
        .collect()
}

/// Load every preset on disk, sorted by name (case-insensitive).
pub fn load_all() -> Vec<ComboPreset> {
    let dir = presets_dir();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => return Vec::new(),
    };

    let mut out: Vec<ComboPreset> = entries
        .flatten()
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "json"))
        .filter_map(|e| {
            let content = fs::read_to_string(e.path()).ok()?;
            serde_json::from_str::<ComboPreset>(&content).ok()
        })
        .collect();

    out.sort_by(|a, b| a.name.to_lowercase().cmp(&b.name.to_lowercase()));
    out
}

/// Save a preset atomically. Rejects presets with zero items because
/// an empty combo has no launch semantics — the UI should catch this
/// earlier, but defending here keeps bad data from reaching disk even
/// through bugs or imports.
pub fn save(preset: &ComboPreset) -> Result<(), String> {
    if preset.items.is_empty() {
        return Err("组合预设至少需要一个模板条目".to_string());
    }
    if preset.name.trim().is_empty() {
        return Err("组合预设名称不能为空".to_string());
    }
    let dir = presets_dir();
    fs::create_dir_all(&dir).map_err(|e| format!("创建预设目录失败: {}", e))?;

    let mut to_write = preset.clone();
    to_write.updated_at = chrono::Utc::now();

    let json = serde_json::to_string_pretty(&to_write)
        .map_err(|e| format!("序列化预设失败: {}", e))?;

    let final_path = preset_path(&preset.id);
    let tmp_path = final_path.with_extension("json.tmp");

    {
        let mut file = fs::File::create(&tmp_path)
            .map_err(|e| format!("创建临时文件失败: {}", e))?;
        file.write_all(json.as_bytes())
            .map_err(|e| format!("写入预设失败: {}", e))?;
        file.sync_all().ok();
    }

    fs::rename(&tmp_path, &final_path)
        .map_err(|e| format!("重命名预设文件失败: {}", e))?;
    Ok(())
}

/// Delete a preset by id. Missing files are treated as success.
pub fn delete(id: &str) -> Result<(), String> {
    let path = preset_path(id);
    match fs::remove_file(&path) {
        Ok(_) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(format!("删除预设失败: {}", e)),
    }
}

/// Report returned by `launch_preset`. Lists which items launched
/// successfully and which failed + why, so the UI can show a summary
/// toast and open any failure details inline.
#[derive(Debug, Clone, Default)]
pub struct LaunchReport {
    pub launched: Vec<String>,
    pub failed: Vec<(String, String)>,
    pub missing_templates: Vec<String>,
}

impl LaunchReport {
    pub fn total_attempted(&self) -> usize {
        self.launched.len() + self.failed.len() + self.missing_templates.len()
    }
}

/// Launch every item in the preset against `project_root`.
///
/// We resolve each `ComboItem.template_id` through `template_manager`
/// at launch time rather than at save time, so that edits to a
/// template apply retroactively to every preset that uses it.
///
/// Failures on individual items are collected but do not short-circuit
/// the loop — a partial launch is often still useful (the user sees
/// which terminals came up and can retry the rest).
pub fn launch_preset(
    project_root: &Path,
    preset: &ComboPreset,
) -> LaunchReport {
    let mut report = LaunchReport::default();

    // Load the template table once; looking up by id is O(n) for each
    // item but the template count is tiny in practice (<100).
    let all_templates = template_manager::load_all();
    let resolve = |id: &str| -> Option<AgentTemplate> {
        all_templates.iter().find(|t| t.id == id).cloned()
    };

    for (idx, item) in preset.items.iter().enumerate() {
        let label = item
            .label
            .clone()
            .or_else(|| resolve(&item.template_id).map(|t| t.name))
            .unwrap_or_else(|| format!("项目 #{}", idx + 1));

        let Some(tpl) = resolve(&item.template_id) else {
            report.missing_templates.push(format!(
                "{} (id={})", label, item.template_id
            ));
            continue;
        };

        let result = terminal_launcher::launch_agent_with_prompt(
            project_root,
            &tpl.agent_type,
            &tpl.permission_mode,
            tpl.initial_prompt.as_deref(),
        );
        match result {
            Ok(()) => report.launched.push(label),
            Err(e) => report.failed.push((label, e)),
        }
    }

    report
}

/// Load a single preset by id. Convenience helper for the command
/// palette and the dashboard "launch combo" dropdown.
#[allow(dead_code)]
pub fn load_by_id(id: &str) -> Option<ComboPreset> {
    let content = fs::read_to_string(preset_path(id)).ok()?;
    serde_json::from_str(&content).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::ComboItem;

    #[test]
    fn save_rejects_empty_items() {
        let p = ComboPreset::new("empty".into());
        // No items — save should refuse without touching disk.
        let err = save(&p).unwrap_err();
        assert!(err.contains("至少需要"));
    }

    #[test]
    fn save_rejects_empty_name() {
        let mut p = ComboPreset::new("".into());
        p.items.push(ComboItem {
            template_id: "x".into(),
            label: None,
        });
        let err = save(&p).unwrap_err();
        assert!(err.contains("名称不能为空"));
    }

    #[test]
    fn launch_report_missing_template_counts() {
        let mut preset = ComboPreset::new("combo".into());
        preset.items.push(ComboItem {
            template_id: "does_not_exist".into(),
            label: Some("phantom".into()),
        });
        // Launch against a clearly-nonexistent dir so the resolver
        // finds nothing on disk; launch_agent_with_prompt would never
        // be called because the template lookup fails first.
        let report = launch_preset(Path::new("/this/does/not/exist"), &preset);
        assert_eq!(report.launched.len(), 0);
        assert_eq!(report.failed.len(), 0);
        assert_eq!(report.missing_templates.len(), 1);
        assert!(report.missing_templates[0].contains("phantom"));
        assert_eq!(report.total_attempted(), 1);
    }
}
