use crate::models::AgentTemplate;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

/// Directory where template JSON files are stored: `~/.agentdesk/templates/`.
fn templates_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".agentdesk")
        .join("templates")
}

fn template_path(id: &str) -> PathBuf {
    templates_dir().join(format!("{}.json", sanitize_id(id)))
}

/// Strip any characters that would escape the templates directory.
/// Template ids are generated by `AgentTemplate::new`, so this is a
/// defensive check — never trust ids coming back from disk.
fn sanitize_id(id: &str) -> String {
    id.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-')
        .collect()
}

/// Load every template on disk, sorted by name (case-insensitive).
pub fn load_all() -> Vec<AgentTemplate> {
    let dir = templates_dir();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => return Vec::new(),
    };

    let mut out: Vec<AgentTemplate> = entries
        .flatten()
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "json"))
        .filter_map(|e| {
            let content = fs::read_to_string(e.path()).ok()?;
            serde_json::from_str::<AgentTemplate>(&content).ok()
        })
        .collect();

    out.sort_by(|a, b| a.name.to_lowercase().cmp(&b.name.to_lowercase()));
    out
}

/// Save a template using atomic write (tmp file + rename) to avoid torn writes.
pub fn save(template: &AgentTemplate) -> Result<(), String> {
    let dir = templates_dir();
    fs::create_dir_all(&dir).map_err(|e| format!("创建模板目录失败: {}", e))?;

    let json = serde_json::to_string_pretty(template)
        .map_err(|e| format!("序列化模板失败: {}", e))?;

    let final_path = template_path(&template.id);
    let tmp_path = final_path.with_extension("json.tmp");

    {
        let mut file = fs::File::create(&tmp_path)
            .map_err(|e| format!("创建临时文件失败: {}", e))?;
        file.write_all(json.as_bytes())
            .map_err(|e| format!("写入模板失败: {}", e))?;
        file.sync_all().ok();
    }

    fs::rename(&tmp_path, &final_path)
        .map_err(|e| format!("重命名模板文件失败: {}", e))?;
    Ok(())
}

/// Delete a template by id. Missing files are treated as success.
pub fn delete(id: &str) -> Result<(), String> {
    let path = template_path(id);
    match fs::remove_file(&path) {
        Ok(_) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(format!("删除模板失败: {}", e)),
    }
}

/// Load a single template by id.
#[allow(dead_code)]
pub fn load_by_id(id: &str) -> Option<AgentTemplate> {
    let content = fs::read_to_string(template_path(id)).ok()?;
    serde_json::from_str(&content).ok()
}
